name: "CI Pipeline"
on:
  pull_request:
    branches:    
      - main    
  push:
    branches:
      - main
    tags:
      - 'release-*'

concurrency: custom_runner

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install cor tools
        run: |
          export PATH="${HOME}/.local/bin:${PATH}"
          which cor 2>&1 >/dev/null || {
            pipx install cor-launcher --index-url https://gitlab.com/api/v4/projects/64628567/packages/pypi/simple
            cor-setup
          }
  #test:
  #  runs-on: self-hosted
  #  needs: build
  #  steps:
  #    - name: make_test
  #      run: script/run-with-docker.sh make BUILD_TYPE=Release test
  #release:
  #  if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
  #  runs-on: self-hosted
  #  needs:
  #    - build
  #    - test
  #  steps:
  #    - name: make_export-pkg
  #      run: script/run-with-docker.sh make BUILD_TYPE=Release export-pkg
  #    - name: publish-release
  #      env:
  #        RELEASE_CONAN_REMOTE: ${{ vars.RELEASE_CONAN_REMOTE }}
  #        RELEASE_CONAN_LOGIN_USERNAME: ${{ vars.RELEASE_CONAN_LOGIN_USERNAME }}
  #        RELEASE_CONAN_PASSWORD: ${{ secrets.RELEASE_CONAN_PASSWORD }}
  #        EXPORT_PKG_ONLY: 1
  #      run: script/run-with-docker.sh script/publish-release.sh
  
